### ISSUE TITLE
Error when trying to call `Client.getme`

### ISSUE THREAD

**Issue by tuxcrafting** [Manishearth/ChatExchange#125]
When I try to call `Client.getme`, I get this error:
```
Traceback (most recent call last):
  File "zalgo.py", line 14, in <module>
    me = client.get_me()
  File "build\bdist.win32\egg\chatexchange\client.py", line 125, in get_me
  File "build\bdist.win32\egg\chatexchange\_utils.py", line 78, in __get__
  File "build\bdist.win32\egg\chatexchange\browser.py", line 235, in _update_chat_fkey_and_user
  File "build\bdist.win32\egg\chatexchange\browser.py", line 218, in _load_user
  File "build\bdist.win32\egg\chatexchange\browser.py", line 226, in user_id_and_name_from_link
ValueError: invalid literal for int() with base 10: 'stackexchange.com'
```
The code:
```
import logging
import time

import chatexchange

#logging.basicConfig(level=logging.DEBUG)

with open("D:/CREDENTIALS") as f: # Change the path to link your credential file looking like `<email> <password>`
    s = f.read().split()

email, password = s

client = chatexchange.Client('stackexchange.com', email, password)
me = client.get_me()
sandbox = client.get_room(1)
sandbox.send_message("test from chatexchange")

time.sleep(2)
```
The credentials are correct, and posting from main account [works](https://chat.stackexchange.com/transcript/message/32258397#32258397).

**Comment by ByteCommander** [comment]
I suspect this has something to do with the privilege level of the bot account (http://chat.stackexchange.com/users/227130/zalgo) which has currently only 30 chat rep points.

**Comment by ByteCommander** [comment]
Modifying `browser.py` around line 230 to look like this:

```
    @staticmethod
    def user_id_and_name_from_link(link_soup):
        print(link_soup)  # <-- added this print line
        user_name = link_soup.text
        user_id = int(link_soup['href'].split('/')[2])
        return user_id, user_name
```

returns the following output for user Zalgo:

    <a href="http://stackexchange.com/users/login?returnurl=http%3a%2f%2fchat.stackexch‌​ange.com%2fchats%2fjoin%2ffavorite">log in</a>

If I test it with my working ByteBot account, the result is this:

    <a href="/users/146720/bytebot" title="ByteBOT">ByteBOT</a>

**Comment by tuxcrafting** [comment]
Modifying the password of the bot fixed the problem.
