### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by bchanda1** [Manishearth/ChatExchange#147]
Hi Manish,

I am getting this error while connecting to SE.

```
Traceback (most recent call last):
  File "C:\Shiro\Shiro-master\Shiro-master\bot.py", line 470, in <module>
    main()
  File "C:\Shiro\Shiro-master\Shiro-master\bot.py", line 80, in main
    client.login(email, password)
  File "C:\Shiro\Shiro-master\Shiro-master\chatexchange\client.py", line 140, in login
    self._br.login_site(self.host)
  File "C:\Shiro\Shiro-master\Shiro-master\chatexchange\browser.py", line 169, in login_site
    'openid_identifier': 'https://openid.stackexchange.com/'
  File "C:\Shiro\Shiro-master\Shiro-master\chatexchange\browser.py", line 190, in _se_openid_login_with_fkey
    response = self.post(post_url, data, with_chat_root=False)
  File "C:\Shiro\Shiro-master\Shiro-master\chatexchange\browser.py", line 113, in post
    return self._request('post', url, data, headers, with_chat_root)
  File "C:\Shiro\Shiro-master\Shiro-master\chatexchange\browser.py", line 102, in _request
    response.raise_for_status()
  File "C:\Python27\lib\site-packages\requests\models.py", line 929, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: https://stackexchange.com/error?aspxerrorpath=/users/authenticate/
```

Any idea's what could be the issue? I have checked everything starting from the user id,password. reputation required for chat room, trying out chat room, manually logging in, etc Not sure what is going wrong here.

**Comment by Filnor** [comment]
I guess it's the same issue as here: https://github.com/Manishearth/ChatExchange/issues/149
