### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by Peter-developer01** [Manishearth/ChatExchange#176]
```none
Exception in thread ChatExchange: RoomPollingWatcher for room #1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/peter/Py/chatexchange/ChatExchange/chatexchange/browser.py", line 801, in _runner
    self.on_activity(activity)
  File "/home/peter/Py/chatexchange/ChatExchange/chatexchange/rooms.py", line 116, in on_activity
    event_callback(event, self._client)
  File "/home/peter/Py/chatexchange/ChatExchange/examples/file.py", line 105, in on_message
    reply = html.unescape(functions.command(message.content, message))
  File "/usr/lib/python3.10/html/__init__.py", line 130, in unescape
    if '&' not in s:
TypeError: argument of type 'NoneType' is not iterable
```

Do someone know how to catch this?

**Comment by Peter-developer01** [comment]
Sorry, this issue is not with ChatExchange library. I'm closing this issue as not planned.
