### ISSUE TITLE
Intermittent login failure

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/ChatExchange#8]
```
Traceback (most recent call last):
  File "report.py", line 18, in <module>
    wrap.login(username,password)
  File "SEChatWrapper.py", line 49, in login
    self.br.loginChatSE()
  File "SEChatBrowser.py", line 67, in loginChatSE
    authToken = chatlogin.find('input', {"name": "authToken"})['value']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Probably due to throttling

**Comment by AWegnerGitHub** [comment]
I receive this error as well (with adjusted line numbers, presumably because of 9 months of development from when this issue was originally open). Prior to today, I was able to log in and have been utilizing this project for about 6 months with no login issues.

	  File "H:\Dev\Git\SE_Chatbot\ChatExchange\chatexchange\client.py", line 140, in login
		self._br.login_se_chat()
	  File "H:\Dev\Git\SE_Chatbot\ChatExchange\chatexchange\browser.py", line 202, in login_se_chat
		auth_token = start_login_soup.find('input', {'name': 'authToken'})['value']
	TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by Filnor** [comment]
Kinda invalided by now as OpenID is now replaced. But on the new login, you may run into a captcha after too many recent logins which blocks you for 5 - 10 minutes.
