### ISSUE TITLE
KeyError that happens at random

### ISSUE THREAD

**Issue by ProgramFOX** [Manishearth/ChatExchange#84]
When I run my chat bots, then sometimes I get a KeyError, which seems to happen at random.

Traceback:
<pre><code>
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "Path\ChatExchange\chatexchange\browser.py", line 625, in _runner
    self.on_activity(json.loads(a))
  File "Path\ChatExchange\chatexchange\rooms.py", line 71, in on_activity
    for event in self._events_from_activity(activity, self.id):
  File "Path\ChatExchange\chatexchange\rooms.py", line 85, in _events_from_activity
    event = events.make(room_event_data, self._client)
  File "Path\ChatExchange\chatexchange\events.py", line 16, in make
    return cls(data, client)
  File "Path\ChatExchange\chatexchange\events.py", line 48, in __init__
    self.room = client.get_room(data['room_id'], name=data['room_name'])
KeyError: 'room_id'</code></pre>

**Comment by hichris1234** [comment]
Smokey is getting this too. I'll take a look, but we'll see if I get anywhere.

**Comment by hichris1234** [comment]
I'm betting as @Manishearth said it has to do with the lazy loading. It looks like room data is lazy-loaded, correct? And if that room data isn't there before an event is created, something like this would occur.
